server:
  port: 7777
spring:
  datasource:
#    url: jdbc:mysql://123.249.107.2:3306/bond?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/citi
#    url: jdbc:mysql://localhost:3306/bond?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
#    password: P@ssword123
    password: 12345678
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    # 开启SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 取消驼峰命名自动转化为下划线命名
#    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:Mapper/*.xml
